version: "3"

services:

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    ports:
      - 6831:6831/udp # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - 6832:6832/udp # accept jaeger.thrift in binary Thrift protocol used by Node.js Jaeger client (because thriftrw npm package does not support compact protocol)
      - 5775:5775/udp # accept zipkin.thrift in compact Thrift protocol (deprecated; only used by very old Jaeger clients, circa 2016)
      - 5778:5778 # serve configs, sampling strategies
      - 4317:4317 # OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # OpenTelemetry Protocol (OTLP) over HTTP
      - 16686:16686 # UI port
      - 14269:14269 # collector admin port: health check at / and metrics at /metrics
      - 9411:9411 # Zipkin compatible endpoint
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  cart:
    image: cart
    build:
      context: cart
      dockerfile: ./Dockerfile
    ports:
      - target: 8001
        published: 8001

  billing:
    image: billing
    build:
      context: billing
      dockerfile: ./Dockerfile
    ports:
      - target: 8000
        published: 8080

  order:
    image: order
    build:
      context: order
      dockerfile: ./Dockerfile
    ports:
      - target: 8002
        published: 8002             